/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Qf4uPqORARc
 */
import { Link } from "react-router-dom";
import { Button } from "../ui/button"
import { account } from "../../appwrite/appwriteConfig";
import { useNavigate } from "react-router-dom";

export function NewHeader({data = {name: ''}}) {
  const {name} = data;
  const navigate = useNavigate()
  return (
    (<header className="flex px-5 items-center h-16 bg-gray-100 px-4 w-full shrink-0">
      <Link className="mr-6" href="#">
        <MountainIcon className="h-6 w-6" />
        <span className="sr-only">Acme Inc</span>
      </Link>
      <Link className="mr-6 text-lg" href="#">
        Home
      </Link>
      <div className="flex items-center space-x-4 ml-auto px-4">
        <div className="text-lg font-semibold text-gray-500 border border-green-300 bg-green-100 p-1 px-3 rounded-3xl">{name}</div>
        <Button onClick={() => {
        account.deleteSessions()
        navigate('/login')
    }}>Logout</Button>
      </div>
    </header>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
